credentials:
  usernames:
    debc:
      email: deb.c@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Debashish Chatterjee
      password: abc # Will be hashed automatically
    rkohli:
      email: rupkohli17@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Rupinder Kohli
      password: abc # Will be hashed automatically
    guest:
      email: rupkohli17@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Guest
      password: guest # Will be hashed automatically
cookie:
  expiry_days: 30
  key: convextradesalgo # Must be string
  name: cookie_convextradesalgo
pre-authorized:
  emails:
  - rupinder.johar.kohli@gmail.com