credentials:
  usernames:
    debc:
      email: deb.c@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: John Smith
      password: abc # Will be hashed automatically
    rkohli:
      email: rupkohli17@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Rebecca Briggs
      password: def # Will be hashed automatically
cookie:
  expiry_days: 30
  key: convextradesalgo # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - rupinder.johar.kohli@gmail.com